version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      ai-sdk:
        patterns:
          - "@ai-sdk/*"
          - "ollama-ai-provider"
          - "ai"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
